services:
  - type: web
    name: my-express-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: FIREBASE_CONFIG
        sync: false  # If you have Firebase credentials, set them manually in Render
